"""auto tables

Revision ID: 922c5f15b806
Revises: 48fd3b9cbf02
Create Date: 2024-02-05 00:36:27.873598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '922c5f15b806'
down_revision: Union[str, None] = '48fd3b9cbf02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.add_column('post', sa.Column('content', sa.String(), nullable=False))
    op.add_column('post', sa.Column('is_published', sa.Boolean(), server_default='TRUE', nullable=False))
    op.add_column('post', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('post', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('post', 'post',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.alter_column('post', 'post',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('post', 'user_id')
    op.drop_column('post', 'created_at')
    op.drop_column('post', 'is_published')
    op.drop_column('post', 'content')
    op.drop_table('votes')
    op.drop_table('user')
    # ### end Alembic commands ###
